Fix build with clang/c++1z due to register keyword
dtoa.cpp:794:5: error: ISO C++1z does not allow 'register' storage class specifier [-Wregister]

Change-Id: I800ba0eb11fb55db8600a0eb937689e082c41c31
Reviewed-by: Simon Hausmann <simon.hausmann@theqtcompany.com>