Fix compilation under precompiled headers: define _CRT_RAND_S
If the macro _CRT_RAND_S is defined, #include <stdlib.h> will define the
rand_s function. All was well before the precompiled headers because
wtf/config.h was always the first header included in WTF and it #defined
at the right place. With precompiled headers, stdlib.h got included from
qglobal.h before the #define took place.

This was a latent bug because the non-JSC parts of QtScript could have
included RandomNumberSeed.h and caused the error.

RandomNumberSeed.h(82) : error C3861: 'rand_s': identifier not found

Change-Id: I88b4b8670604b35ca694c02522324ac3083ed2b4
Reviewed-by: Sergio Ahumada <sahumada@blackberry.com>
Reviewed-by: Oswald Buddenhagen <oswald.buddenhagen@digia.com>